from __future__ import annotations

import re

from app.agents.base_agent import BaseAgent
from app.core.logger import logger
from app.models.task import Task
from app.services.llm.router import LLMRouter


class CoderAgent(BaseAgent):
    """
    Coder Agent.

    Converts a Planner Task into a complete software project
    represented as FILE: path/to/file.ext blocks.

    Flow:

        PlannerAgent
              ↓
        CoderAgent
              ↓
        ProjectBuilder
              ↓
        Generated Project / ZIP
    """

    # --------------------------------------------------
    # Configuration
    # --------------------------------------------------

    MIN_RESPONSE_LENGTH = 50

    MAX_FILE_PATH_LENGTH = 250

    # Files that should never be generated by the LLM.
    FORBIDDEN_PATH_PATTERNS = (
        ".env",
        ".env.local",
        ".env.production",
        ".env.development",
        "id_rsa",
        "id_ed25519",
        ".pem",
        ".key",
        "__pycache__",
        ".pyc",
        "node_modules",
        ".git/",
    )

    # --------------------------------------------------
    # Main
    # --------------------------------------------------

    async def run(
        self,
        task: Task,
    ) -> str:

        logger.info("=" * 60)
        logger.info("Coder Agent Started")
        logger.info("=" * 60)

        if not task:
            raise ValueError(
                "CoderAgent received an empty task."
            )

        if not task.title:
            raise ValueError(
                "Task title is required."
            )

        if not task.description:
            raise ValueError(
                "Task description is required."
            )

        logger.info(
            f"Generating project for task: {task.title}"
        )

        # --------------------------------------------------
        # Get LLM
        # --------------------------------------------------

        llm = LLMRouter.get_llm()

        # --------------------------------------------------
        # Format Planner Steps
        # --------------------------------------------------

        steps = "\n".join(
            f"{index}. {step}"
            for index, step in enumerate(
                task.steps,
                start=1,
            )
        )

        # --------------------------------------------------
        # Build Prompt
        # --------------------------------------------------

        prompt = self._build_prompt(
            task=task,
            steps=steps,
        )

        logger.info(
            "Generating complete software project..."
        )

        # --------------------------------------------------
        # Generate
        # --------------------------------------------------

        response = await llm.generate(prompt)

        if not response:
            raise RuntimeError(
                "Coder Agent received an empty response from LLM."
            )

        logger.info(
            f"Raw coder response length: {len(response)} characters."
        )

        # --------------------------------------------------
        # Normalize Response
        # --------------------------------------------------

        response = self._normalize_response(response)

        # --------------------------------------------------
        # Validate Response
        # --------------------------------------------------

        self._validate_response(response)

        logger.info(
            f"Validated coder response: {len(response)} characters."
        )

        logger.info("=" * 60)
        logger.info("Coder Agent Finished")
        logger.info("=" * 60)

        return response

    # --------------------------------------------------
    # Prompt Builder
    # --------------------------------------------------

    def _build_prompt(
        self,
        task: Task,
        steps: str,
    ) -> str:
        """
        Build the system prompt used to generate the project.
        """

        return f"""
You are AutoDev AI.

You are an expert:

- Software Architect
- Principal Software Engineer
- Backend Engineer
- Frontend Engineer
- Database Engineer
- DevOps Engineer
- QA Engineer
- Security Engineer

Your job is to generate a COMPLETE, EXECUTABLE software project
from the implementation plan provided below.

============================================================
PROJECT
============================================================

TITLE:
{task.title}

DESCRIPTION:
{task.description}

IMPLEMENTATION PLAN:
{steps}

============================================================
ARCHITECTURE
============================================================

First internally determine:

1. Best programming language
2. Best framework
3. Best project architecture
4. Required dependencies
5. Database requirements
6. API requirements
7. Frontend requirements
8. Testing requirements
9. Configuration requirements
10. Deployment requirements

Do NOT explain these decisions in your response.

============================================================
PROJECT REQUIREMENTS
============================================================

Generate the COMPLETE project.

The generated project must contain all required source files.

Depending on the project, include appropriate files such as:

README.md
.gitignore
.env.example
requirements.txt
package.json
package-lock.json when appropriate
Dockerfile
docker-compose.yml when appropriate
configuration files
backend source code
frontend source code
database models
API routes
services
utilities
tests
documentation

Do not generate unnecessary technologies.

For example:

Do NOT add React if the project does not need a frontend.

Do NOT add MongoDB if SQLite is sufficient.

Do NOT add Docker unless it is useful.

Choose a simple, maintainable architecture.

============================================================
CODE QUALITY
============================================================

Every generated file must:

- Be complete.
- Be executable.
- Use correct syntax.
- Use meaningful names.
- Follow clean-code principles.
- Avoid unnecessary duplication.
- Handle errors properly.
- Use appropriate logging.
- Use type hints where applicable.
- Include useful docstrings where appropriate.
- Have valid imports.
- Use dependencies that actually exist.
- Avoid broken references.

Never generate:

TODO
FIXME
PLACEHOLDER
PSEUDOCODE
EMPTY IMPLEMENTATIONS
"implement this later"
"add your code here"
"your API key here"

Never leave functionality incomplete.

============================================================
SECURITY
============================================================

Never generate real secrets.

Never generate:

- API keys
- passwords
- private keys
- access tokens
- credentials

Use environment variables through:

.env.example

Example:

OPENAI_API_KEY=
DATABASE_URL=

Never create an actual .env file.

============================================================
TESTING
============================================================

Generate executable tests.

At minimum, test the important application functionality.

For Python:

Use pytest when appropriate.

For JavaScript/Node.js:

Use an appropriate testing framework.

Tests must be real executable tests.

============================================================
README
============================================================

README.md must contain:

1. Project Overview
2. Features
3. Technology Stack
4. Project Structure
5. Installation
6. Configuration
7. Environment Variables
8. Usage
9. API Documentation when applicable
10. Running the Application
11. Running Tests
12. Deployment
13. License

============================================================
IMPORTANT OUTPUT FORMAT
============================================================

Your response will be parsed automatically by AutoDev AI.

Therefore you MUST follow this format EXACTLY.

Every file MUST start with:

FILE: relative/path/to/file.ext

Then provide the complete file contents.

Example:

FILE: README.md
# My Project

Project description.

FILE: requirements.txt
fastapi
uvicorn

FILE: app/main.py
from fastapi import FastAPI

app = FastAPI()

IMPORTANT:

- FILE: must be at the beginning of a new line.
- Use relative paths only.
- Never use absolute paths.
- Do not prefix FILE: with markdown.
- Do not use ``` code fences.
- Do not use markdown around file names.
- Do not explain files outside the file blocks.
- Do not add text before the first FILE:
- Do not add text after the final file.
- Do not summarize the project.
- Do not include analysis.
- Do not include explanations.
- Do not include "Here is your project".
- Do not include "Sure".
- Do not include "Below is".
- Do not include comments outside files.

============================================================
FILE PATH RULES
============================================================

Use relative project paths.

VALID:

FILE: README.md

FILE: requirements.txt

FILE: app/main.py

FILE: tests/test_main.py

INVALID:

FILE: C:\\Users\\user\\project\\app.py

FILE: /home/user/project/app.py

FILE: ./../../secret.txt

FILE: ..\\secret.txt

Do not use:

..

in file paths.

============================================================
IMPORTANT
============================================================

Return ONLY project files.

Start immediately with:

FILE:

Do not generate anything before it.

Do not generate anything after the final file.

The project must be executable without manual modification.
"""

    # --------------------------------------------------
    # Response Normalization
    # --------------------------------------------------

    def _normalize_response(
        self,
        response: str,
    ) -> str:
        """
        Normalize common formatting mistakes made by LLMs.
        """

        response = response.strip()

        # Remove accidental leading/trailing markdown fences.
        response = re.sub(
            r"^```(?:text|plaintext)?\s*",
            "",
            response,
            flags=re.IGNORECASE,
        )

        response = re.sub(
            r"\s*```$",
            "",
            response,
        )

        response = response.strip()

        # Sometimes the model returns:
        #
        # "Here is your project:"
        #
        # before FILE:.
        #
        # Remove everything before the first FILE marker.
        first_file = response.find("FILE:")

        if first_file > 0:
            logger.warning(
                "Removing text before first FILE: marker."
            )

            response = response[first_file:]

        return response.strip()

    # --------------------------------------------------
    # Validation
    # --------------------------------------------------

    def _validate_response(
        self,
        response: str,
    ) -> None:
        """
        Validate that the generated response is compatible
        with ProjectBuilder.
        """

        if not response:
            raise RuntimeError(
                "Coder Agent returned an empty project."
            )

        if len(response) < self.MIN_RESPONSE_LENGTH:
            raise RuntimeError(
                "Coder Agent response is too short to be a project."
            )

        if not response.startswith("FILE:"):
            raise RuntimeError(
                "Invalid coder output. "
                "Project must start with FILE:."
            )

        file_blocks = self._extract_file_blocks(
            response
        )

        if not file_blocks:
            raise RuntimeError(
                "Coder Agent generated no project files."
            )

        logger.info(
            f"Coder generated {len(file_blocks)} file(s)."
        )

        for path, content in file_blocks:

            self._validate_file_path(path)

            if not content.strip():
                raise RuntimeError(
                    f"Generated file is empty: {path}"
                )

            logger.debug(
                f"Validated generated file: {path}"
            )

    # --------------------------------------------------
    # File Parser
    # --------------------------------------------------

    def _extract_file_blocks(
        self,
        response: str,
    ) -> list[tuple[str, str]]:
        """
        Extract FILE blocks from coder output.

        Expected format:

        FILE: app/main.py
        <content>

        FILE: requirements.txt
        <content>
        """

        pattern = re.compile(
            r"(?m)^FILE:\s*(.+?)\s*$"
        )

        matches = list(
            pattern.finditer(response)
        )

        if not matches:
            return []

        files: list[tuple[str, str]] = []

        for index, match in enumerate(matches):

            path = match.group(1).strip()

            content_start = match.end()

            if index + 1 < len(matches):
                content_end = matches[
                    index + 1
                ].start()
            else:
                content_end = len(response)

            content = response[
                content_start:content_end
            ].strip()

            files.append(
                (
                    path,
                    content,
                )
            )

        return files

    # --------------------------------------------------
    # File Path Validation
    # --------------------------------------------------

    def _validate_file_path(
        self,
        path: str,
    ) -> None:
        """
        Validate generated project file paths.
        """

        if not path:
            raise RuntimeError(
                "Generated file contains an empty path."
            )

        if len(path) > self.MAX_FILE_PATH_LENGTH:
            raise RuntimeError(
                f"Generated file path is too long: {path}"
            )

        # Normalize Windows separators.
        normalized = path.replace(
            "\\",
            "/",
        )

        # Must be relative.
        if normalized.startswith("/"):
            raise RuntimeError(
                f"Absolute file path is not allowed: {path}"
            )

        # Windows drive path.
        if re.match(
            r"^[A-Za-z]:",
            normalized,
        ):
            raise RuntimeError(
                f"Absolute Windows path is not allowed: {path}"
            )

        # Prevent directory traversal.
        parts = normalized.split("/")

        if ".." in parts:
            raise RuntimeError(
                f"Directory traversal is not allowed: {path}"
            )

        # Prevent dangerous files.
        lower_path = normalized.lower()

        for forbidden in self.FORBIDDEN_PATH_PATTERNS:

            if forbidden in lower_path:
                raise RuntimeError(
                    f"Forbidden file path generated: {path}"
                )
